version: "2"
linters:
  exclusions:
    rules:
      - linters:
          - staticcheck
        text: "QF1001:" # De Morgan's Law (`!(a && b)` -> `!a || !b`)
    generated: lax
    presets:
      - comments
      - common-false-positives
      - std-error-handling
      - legacy
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
