#!/bin/bash
set -eo pipefail
cd $(dirname $0)

# Install SeaweedFS
if ! weed version >/dev/null 2>&1; then
    rm -f install.sh
    wget https://raw.githubusercontent.com/seaweedfs/seaweedfs/master/install.sh
    bash install.sh --dir ~/.local/bin
    PATH=~/.local/bin:$PATH
    rm -f install.sh
fi

rm -rf coverage
mkdir coverage
failures=0
echo '*** test ***'
if ! go test -v -coverpkg=./... -coverprofile=coverage/coverage.cov ./... ${1+"$@"}; then
    failures=1
fi
go tool cover -html=coverage/coverage.cov -o coverage/coverage.html
echo "Check coverage results coverage/coverage.html"
if [[ $failures == 1 ]]; then
    echo "Some tests failed"
    exit 2
fi
echo "All tests passed or were skipped."
