name: qfs build
on:
  push:
    branches:
      - work
  pull_request:
    branches:
      - work
env:
  AWS_REGION: "us-east-1"
jobs:
  Build:
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: $${ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: Test
        run: ./test_all
