name: qfs build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  AWS_REGION: "us-east-1"
jobs:
  Build:
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        platform:
          - os: ubuntu-latest
            install: ''
          - os: macos-latest
            install: '--install-minio'
    runs-on: ${{ matrix.platform.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: Test
        run: ./test_all ${{ matrix.platform.install }}
